# voando_a_caminho_com_foco_obstaculo_girando_fim.py
# Estado: VOANDO_A_CAMINHO_COM_FOCO_OBSTACULO_GIRANDO_FIM

from drone_inspetor.common.enums import DroneStateDescription as DS
from drone_inspetor.nodes.drone_node.fsm.states._obstaculo_base import BaseObstaculoGirandoFimState


class VoandoACaminhoComFocoObstaculoGirandoFimState(BaseObstaculoGirandoFimState):
    NEXT_DESVIADO_ID = DS.VOANDO_A_CAMINHO_COM_FOCO_OBSTACULO_DESVIADO
